### ISSUE TITLE
2024 Redesign

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/seanmcp.com#65]
## Goals

- Incremental release
- Simplify:
  - Markup
  - Tooling

## Tasks

- [x] Remove byline e8dc6cb32ef8ef8276af46dbce2711a876f320cd
- [x] Decrease heading size/weight https://github.com/SeanMcP/seanmcp.com/pull/66
- [ ] Fine-tune typography
- [x] Simplify footer e8dc6cb32ef8ef8276af46dbce2711a876f320cd
- [x] Better search https://github.com/SeanMcP/seanmcp.com/pull/67
